### PR TITLE
Update zh-Hant Localizable

### PR DESCRIPTION
**Pull request by mumuisdog**

### CODE REVIEW

**Comment by dayanch96** [comment]
Now, if you enable "Update Localization" options it will automatically use your translation from github. Thanks

**Comment by dayanch96** [comment]
Guess you forgot to translate ‘Premium’ string

**Comment by mumuisdog** [comment]
> Guess you forgot to translate ‘Premium’ string

I think the best translation is premium.
Ex:YouTube Premium

**Comment by dayanch96** [comment]
its not the same, but guess its better to use Infuse Pro instead

**Comment by mumuisdog** [comment]
> its not the same, but guess its better to use Infuse Pro instead

Good idea Done

**Comment by dayanch96** [comment]
lets keep Premium for now

**Pull request merged**
